update firebase-tools version
w9jds/firebase-action pull request #129
Opened 2022-04-25 20:22 UTC by grascioni

Hi, it'd be great if you accepted this PR, as my project's needs an updated version of firebase-tools.

Specifically, we need a bug fix where functions' memory configurations weren't preserved in batched function deploys.
See https://github.com/firebase/firebase-tools/releases/tag/v10.3.0.

BTW, latest version of the package is 10.7.1, so I just went ahead with that one. Thx!

2022-04-26 02:38 UTC, aravindvnair99 requested changes

2022-04-26 02:38 UTC, aravindvnair99 commented on Dockerfile
>  RUN npm i -g npm@8.3.1
```suggestion
RUN npm i -g npm@8.7.0
```

2022-04-26 02:39 UTC, aravindvnair99 commented
@grascioni `npm` version can also be updated along with this.

2022-05-14 18:41 UTC, w9jds commented
I'm going to merge this in a bit, I'm working on making the deployment use versions.

2022-05-14 19:03 UTC, merged